final products = [
  {
    'id': '0',
    'title': 'Man\'s Shirt',
    'price': 700.00,
    'imageurl': 'assets/images/shirt.png',
    'sizes': ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    'id': '1',
    'title': 'Man\'s T-Shirt',
    'price': 450.00,
    'imageurl': 'assets/images/R_tshirt.png',
    'sizes': ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    'id': '2',
    'title': 'Man\'s T-Shirt',
    'price': 600.00,
    'imageurl': 'assets/images/w_tshirt.png',
    'sizes': ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    'id': '3',
    'title': 'Man\'s T-Shirt',
    'price': 450.00,
    'imageurl': 'assets/images/blue_tshirt.png',
    'sizes': ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    'id': '4',
    'title': 'Man\'s Pant',
    'price': 700.00,
    'imageurl': 'assets/images/pant.png',
    'sizes': ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    'id': '5',
    'title': 'Man\'s Jeans',
    'price': 800.00,
    'imageurl': 'assets/images/jeans.png',
    'sizes': ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    'id': '6',
    'title': 'Women\'s Jeans Pant',
    'price': 750.00,
    'imageurl': 'assets/images/jeans2.png',
    'sizes': ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    'id': '7',
    'title': 'Man\'s T-Shirt',
    'price': 400.00,
    'imageurl': 'assets/images/B_tshirt.png',
    'sizes': ['S', 'M', 'L', 'XL', 'XXL'],
  },
];
